version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'sass'

    groups:
      dependencies:
        patterns:
          - '*'

    open-pull-requests-limit: 20
